# Use an official Python runtime as a parent image
FROM python:3.13-slim-bookworm
# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh
# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh
# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
# Set the working directory
WORKDIR /code
# Copy the pyproject.toml and uv.lock files
COPY pyproject.toml uv.lock /code/
# Install dependencies using uv
RUN uv sync --frozen
# Copy the application code
COPY ./helper_lib /code/helper_lib/
COPY ./main.py /code/
# Copy the trained model
COPY ./checkpoints /code/checkpoints/
# Command to run the application
CMD ["uv", "run", "fastapi", "run", "main.py", "--port", "80"]
